language: cpp
os:
    - freebsd

compiler: gcc
env: CONFIG=Release
group: stable

script:
    - |
      qmake -v
      ./configure.py
      make
      ./configure.py --without-qt-ui --debug-mode --test
      make
      ./scripts/tool.sh --run-tests
      ./scripts/tool.sh --run-func-tests --debug
addons:
  pkg:
    - botan2
    - qt5
    - pkgconf
